### ISSUE TITLE
[ologram] P-values equal to zero  when nb_intersections_true and nb_intersections_esperance_shuffled are equal to zero.

### ISSUE THREAD

**Issue by dputhier** [dputhier/pygtftk#72] opened 2019-03-27 15:24 UTC
I have added a -j argument to ologram that controls the ways bars are sorted in the diagram (dev branch). I realized that the results regarding some feature are weirds. This is true especially for the example from the doc where we look at gene_biotype(see attach files).
[00_ologram_stats.txt](https://github.com/dputhier/pygtftk/files/3013890/00_ologram_stats.txt)

**Here, clearly TEC and others should not have a p-value of zero.**

    gtftk get_example -q -d mini_real -f '*' 
    gtftk get_example -d mini_real | gtftk ologram -m gene_biotype -p ENCFF112BHN_H3K4me3_K562_sub.bed -c hg38.genome -D -n  -if example_pa_02.pdf -V 1 -j  summed_bp_overlaps_pvalue -K ologram_output

![image](https://user-images.githubusercontent.com/1831198/55088261-b9e60500-50ab-11e9-8a51-434687d354fc.png)

**Comment by qferre** [comment] 2019-03-29 09:38
_It's not a bug, it's a feature.<sup>TM</sup>_

The reasons those p-values are zero is because when fitting a NB is impossible, an empirical p-value is returned.

Maybe I could drop the empirical p-value altogether ? It may cause more confusion than it's worth. Then I could maybe just return a np.nan

**Comment by qferre** [comment] 2019-03-29 10:38
I dropped the empirical p-values. Should now return NaNs.

**Comment by dputhier** [comment] 2019-03-29 10:40
Cool. You should the corresponding sha to your comments. It makes it easier to check the associated commit.

**Comment by dputhier** [comment] 2019-03-29 10:41
In develop ?

**Comment by qferre** [comment] 2019-03-29 10:47
It is now. Commit is 3872d5e9be8faa54e51db4a5c14202f591f75640

I had not put the commit sha in my previous number because I had not commited them yet, sorry.

**Comment by qferre** [comment] 2019-04-02 06:32
To prevent pandas from panicking when printing the dataframe into a file, I return '-1' instead of NaN. The graph code will translate any '-1' p-value into a 'NA' for display. Closing.

**Closed by qferre** 2019-04-02 06:32 UTC
